CREATE TABLE IF NOT EXISTS app_user (
    id VARCHAR(60) DEFAULT UUID() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastName VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(255) NOT NULL
);
